import Head from "next/head";
import Image from "next/image";
import Banner from "../../components/Banner";
import Header from "../../components/Header";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>TravelMate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* Banner */}
      <Banner />
    </div>
  );
}
